# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
release:
  github:
    owner: Siroshun09
    name: dlpaper
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dlpaper/main.go
    binary: dlpaper
    ldflags:
      - -s -w -X main.build={{.Version}}
archives:
  - id: dlpaper
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
